name: Build and deploy Node.js app to Azure Web App - handmadehubbackend

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'  # Use '22.x' only if your backend truly needs latest features

      - name: Install dependencies and optional build
        working-directory: backend
        run: |
          npm install
          npm run build --if-present

      - name: Archive backend build
        run: |
          cd backend
          zip -r ../backend-release.zip ./

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: backend-artifact
          path: backend-release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: backend-artifact

      - name: Unzip artifact
        run: unzip backend-release.zip -d backend

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_5C2301FCE9654EA4A87F373BF044D154 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_4253428FB48E411CB04361E87F386B7C }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_14A94743170C47068E60F0E95CCF79D3 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'handmadehubbackend'         # Your Azure App Service name
          slot-name: 'Production'
          package: backend
